version: '3.7'

volumes:
  mysql_data:
      driver: local

x-common-variables: &common-variables
  eureka.client.serviceUrl.defaultZone: http://registry:8080/eureka
  eureka.instance.non-secure-port: 8080
  spring.security.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:8080/auth/realms/mycompany
  SPRING_MAIN_BANNER-MODE: 'off'

services:
  mariadb:
    image: mariadb
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    ports:
      - "3306:3306"
      # Copy-pasted from https://github.com/docker-library/mariadb/issues/94
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - /tmp:/tmp
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "9090:8080"
    depends_on:
      - mariadb

  registry:
    image: dhananjay12/oauth2-eureka-server:latest
    environment:
      <<: *common-variables
    ports:
      - "8761:8080"
  resource-server:
    image: dhananjay12/oauth2-resource-server:latest
    ports:
      - "7779:8080"
    environment:
      <<: *common-variables
    links:
      - registry
      - keycloak
  reactive-resource-server:
    image: dhananjay12/oauth2-reactive-resource-server:latest
    ports:
      - "7778:8080"
    environment:
      <<: *common-variables
    links:
      - registry
      - keycloak
  api-gateway:
    image: dhananjay12/oauth2-api-gateway:latest
    ports:
      - "7777:8080"
    environment:
      <<: *common-variables
    links:
      - registry
      - keycloak