# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest
    name: Verify and Build Images
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup java 11.0.x
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x

      - name: Verify
        run: mvn -B verify

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push images
        run: mvn clean package jib:dockerBuild
